version: 2
jobs:
  test:
    working_directory: ~/test
    docker:
      - image: circleci/golang:1.11
        environment:
          MONGODB_URI: mongodb://admin:password@127.0.0.1:27017/test
      - image: mongo:3.6-xenial
        ports:
          - "27017:27017"
    steps:
      - checkout
      - run:
          name: install mongo client
          command: |
            sudo apt-get install -y mongodb-clients
      - run:
          name: wait for mongodb container to be up
          command: |
            ./wait-for-it.sh 127.0.0.1:27017 -t 120
      - run:
          name: create admin user for mongo
          command: |
            mongo --eval 'db.createUser({user: "admin", pwd: "password", roles:[{ role: "userAdminAnyDatabase", db: "admin" } ] });'
      - run:
          name: check if user persists
          command: |
            mongo --eval 'db.getUsers()'

workflows:
  version: 2
  workflow:
    jobs:
      - test